# Commit this file to argocd-root at:
#   environments/aws/staging/sre-agent-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sre-agent-staging-aws
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            clusters.netlify.com/name: services-cmh-stag-1
  template:
    metadata:
      name: "sre-agent-{{nameNormalized}}"
      labels:
        releng.netlify.com/application: "sre-agent"
        releng.netlify.com/environment: staging
    spec:
      project: "netlify-apps"
      source:
        repoURL: git@github.com:netlify/argocd-root.git
        path: applications/aws/staging/sre-agent
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: sre-agent-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
